sudo: required
os: linux
language: minimal
addons:
  apt:
    packages:
    - docker-ce
git:
  depth: 4
services:
  - docker

before_install:
  - docker pull lacledeslan/steamcmd:linux
  - docker pull debian:stretch-slim

script:
  - docker version
  - docker build --no-cache --tag lltest/gamesvr-goldsource --tag lacledeslan/gamesvr-goldsource --build-arg BUILDNODE=TravisCI --build-arg SOURCE_COMMIT="$TRAVIS_COMMIT" ./linux
  - docker run -it --rm lltest/gamesvr-goldsource ./ll-tests/gamesvr-goldsource.cstrike.sh
  - docker run -it --rm lltest/gamesvr-goldsource ./ll-tests/gamesvr-goldsource.czero.sh
  - docker run -it --rm lltest/gamesvr-goldsource ./ll-tests/gamesvr-goldsource.dmc.sh
  - docker run -it --rm lltest/gamesvr-goldsource ./ll-tests/gamesvr-goldsource.dod.sh
  - docker run -it --rm lltest/gamesvr-goldsource ./ll-tests/gamesvr-goldsource.gearbox.sh
  - docker run -it --rm lltest/gamesvr-goldsource ./ll-tests/gamesvr-goldsource.hldm.sh
  - docker run -it --rm lltest/gamesvr-goldsource ./ll-tests/gamesvr-goldsource.ricochet.sh
  - docker run -it --rm lltest/gamesvr-goldsource ./ll-tests/gamesvr-goldsource.tfc.sh

notifications:
  slack:
    secure: FGEMATNIgCnIlkRB7i8URUc1rNTr4m5PoHtVYjjsmjQz/dx/n3OxVWaKizckmxHsKV3kfy2NXBhUiA3HMbLm+8CTFUPST8dVDy8hFjfLmQNhZioNNQe31sajXj5g2SkZRMPiKY9m4xaJOlp5016f72HXZAW1MxqHuco/u+yoLmibopIadastrYURn9fTX2cQ1OE/22JfecdDD94wsZuMJQr9DySXPrpvY/ajJnUEFl/Kt/8RK4VI8VC3M0xUliOIlzgPRnV44YtkdpFbRknIq6UDpn+jTHZHpAm+b4ehW9G5scSp9vZqKHCylqSLLqp0Ec4nkrKa8vcdNDfJMsAScYimVWk23fjrGFqTPd82uJXihmD9rN+s5sVzPP7MXCBPg47A8r8GY/eHDxtuS4g8UAoy68LC7FKhUCiHExebpATH78npCyXmsCX9v8R6AEuB2sfKPEbSRcF7DDgVMfUFKfFFyw8XPaZSzBsxY9Ao0MmUf+p63TVJRWuSQKBm75XsWtSBEuIqrlS6HYZ8Nrs0WO5cSq0GcXzOrMa55c9h01bW8iMuJDOISAEPgKCgpV/lwztVzi6YVFrKuzfFymj7KIa6RveRbgqzKK5BS/cqBV+eycOoIdwnjxG9n8eVL49gBmP87/wpCaYR6LHlm231rGQU30c8GLAkOsSJ2lspQ6Y=

before_deploy:
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin;
deploy:
  provider: script
  script: docker push lacledeslan/gamesvr-goldsource
  on:
    branch: master
after_deploy:
  - curl -X POST https://hooks.microbadger.com/images/lacledeslan/gamesvr-goldsource/$MICROBADGER_TOKEN
